### ISSUE TITLE
Survive Vac Wave?

### ISSUE THREAD

**Issue by toequila** [Jire/Abendigo#63]
Did abendigo survive the vac wave? I have multiple accounts that I play on and was wondering if it was safe to use again. Thanks

**Comment by ElectrickFun** [comment]
Ive played today around 4 games and i didnt get vac banned.

**Comment by cra88y** [comment]
Yes it appears to be safe :)

**Comment by davewolax** [comment]
I have been using this cheat for more than 3 month and so far NO VAC ban. recently I got bored and set the SMOOTHING to 50f (which is maximum aim) in FOVAim and get 100% headshot in all matches (not competitive) and I get reported/kicked all the time by people in casual and deathmatch games and still no ban. I've been doing this for almost a month and nothing happened.

I don't suggest doing this on competitive because if you get overwatch, it would be too obvious and you get your self banned.
But since Valve didn't implement any sort of overwatch system on non-competitive matches. there is no way you get a ban and the report system is a joke in non-comp matches and nothing happens (so far) because this cheat is not detected at all.

You can pretty much get 100+ kills in casual matches and nothing can happen to you.

**Comment by bradylangdale** [comment]
Also VAC can't really detect Abendigo because of the fact everyone has a different signature and changing if you recompile. Although getting untrusted is possible, but Abendigo has some pretty good limits. It's mainly a legit hacks if you don't modify it. Overwatch bans are evaded by getting less than 10-11 reports in competitive is 24 hours, which means one blatant game per day and it must be 24 hours later.

**Comment by davewolax** [comment]
@bradylangdale You're right. but there is better way, build up a team of 5 with your best friends so you can play 2-3 blatant game once every 24 hours because only the opposite team might report you! have your fun go full hack 100% HS aim and win.

**Comment by Jire** [comment]
Yes we survived the wave, and still seem to be going strong!
