### ISSUE TITLE
Might be detected

### ISSUE THREAD

**Issue by Jedi-Code** [Jire/Abendigo#70]
I got VAC banned after using this, however i was also using an external bhop script at the time called PolyHop, this was compiled using Merccy's Polyhack compiler, which apparently generates a new signature when you build it, so no 2 people using the hack were supposed to have the same signature. I dont know if PolyHop or Abendigo was detected, or both. Also FOVAIM doesnt always work properly, sometimes you will suddenly snap 90 degrees right while shooting, further more you should consider adding a 'pistol mode' to it which disables recoil control when using pistols, ofc this would be easy to do if the community made it and uploaded it to abendigo.org or whatever the domain was, too bad that some ass had it taken down

**Comment by ElectrickFun** [comment]
Can somebody comfirm this?

**Comment by davewolax** [comment]
I have been using this cheat for more than 4 month now and so far NO VAC ban. 

I recently got bored and set the SMOOTHING to 50f (which is maximum aim) in FOVAim and get 100% headshot in all matches every time! (not competitive).
I get reported/kicked by players in casual and deathmatch games and still no ban. I've been doing this for almost a month and nothing happened.

I don't suggest doing this on competitive because if you get overwatch, it would be too obvious and you get your self banned.
But since Valve didn't implement any sort of overwatch system on non-competitive matches. there is no way you get a ban and the report system is a joke in non-comp matches and nothing happens (so far) because this cheat is not detected at all.

You can pretty much get 100+ kills in casual matches and nothing can happen to you.

And in competitive matches, try to pretend a bit and don't look at other player through the wall. in case you get overwatch, thats the first thing that will get you intro trouble. just play and enjoy the game. build a strong team who use this cheat which will lower the chance of your own team reporting you. and you can easily climb up to Global Elite.

**Comment by ElectrickFun** [comment]
@davewolax 
I understand that but it might have gotten detected recently as vac got an recent update(about 18 hours ago September 20, 2016 – 21:09:42 UTC) so i was wondering if thats what detected it.

**Comment by davewolax** [comment]
Let me open up CS:GO I will tell you in a minute.

**Comment by davewolax** [comment]
Not banned. clean and ready to play.

**Comment by Jire** [comment]
Can you post a screenshot of the in-game message? There are no reports of bans from other people.

**Comment by MaGoKz** [comment]
Still Undetected, Fuck yeah! I Have been using this more than " 6 Months " This ShiT is DOPE! \m/

**Comment by ElectrickFun** [comment]
Ive played yesterday like 6 games and nothing happened.So yea its still undetected.

**Comment by dingdoungr** [comment]
Hey might of been using the controller 
Cause he says sometimes he aim does weird shit and when I use to use the controller it did the same, also controller gets u a vac ban

**Comment by bradylangdale** [comment]
This is not true whats so when the controller is talking to the hacks
themselves over a local network it is IMPOSSIBLE for the vac to even see
that it exist because vac only checks on what writing to the game memory.
It will always the undetected because the signature is unique if you got
banned its because you built and never rebuilt and eventually vac detected
a repeated in the signature.

**Comment by ElectrickFun** [comment]
I rebuild it almost everyday cause im always messing around with values and such.

**Comment by Jire** [comment]
@bradylangdale It's more so that due to the dated design of Abendigo, using multiple threads to access the same areas of memory can cause some very funky behaviors, especially when paired with the caching system. Because the controller allows you to toggle aim plugins, the cached values may be invalid on resume which can cause a flick.

Charlatano uses a single native thread with fibers ("green threads") to allow suspension for sleeps. This keeps all the data intact, and more importantly keeps the programming paradigm straightforward by eliminating the need to care for concurrency.

**Comment by dingdoungr** [comment]
@Jire Is the charlatano ready to be used? cause im a big fan of your work :P might of seen me on some of ur vids and mpgh page :P

**Comment by bradylangdale** [comment]
@Jire Oh ok I never about that when you're toggle. Is there any reason why the controller isn't just built into Abendigo, instead on using a local network?

**Comment by man4red** [comment]
I can confirm this 

> Also FOVAIM doesnt always work properly, sometimes you will suddenly snap 90 degrees right while shooting
